[tool.black]
line-length = 79
skip-string-normalization = true
target-version = ['py37']

[tool.doks]
auto = true

[tool.poetry]
name = "safer"
version = "4.10.1"
description = "🧿 A safer writer for files and streams 🧿"
authors = ["Tom Ritchford <tom@swirly.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8"

[tool.poetry.group.dev.dependencies]
coverage = "*"
flake8 = "*"
pytest = "*"
readme-renderer = "*"
tdir = "*"
toml = "*"
pyyaml = "*"


[tool.coverage]
[tool.coverage.run]
branch = "True"
source = "safer"

[tool.coverage.report]
fail_under = "90"
skip_covered = "True"
exclude_lines = ["", "pragma: no cover", "if False:", "if __name__ == .__main__.:", "raise NotImplementedError"]
[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
